### ISSUE TITLE
Desired Backend Features

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebblestore-api#12]
- [ ]  Ability to provide watchfaces page app lists

- [ ] Ability for an anonymous (we have to moderate this to only allow a user to add one and only to remove the one he added) user to add or remove a thumbs up 

- [ ] Ability to provide watchfaces slider images/categories

- [ ]  Ability to provide apps page lists

- [ ]  Ability to provide apps slider images/categories

- [x]  Ability to provide app tags

- [x]  Ability to provide author page

- [x]  Ability to make searches

- [ ] Implement pagination or infinite scroll (with @pebble-dev/frontend )

- [x]  Ability to provide app/watchface details

- [x]  Ability to provide app versions

- [ ] #21 Have an admin/curator login

- [ ] Ability for admin/curator to add slider images

- [ ] Ability for admin/curator to modify lists like featured apps

- [ ] Ability for admin to add or delete apps

- [ ] Ability for developers to make their [archive apps Rebble Store Ready](https://github.com/pebble-dev/rebble-store/issues/99)

- [ ] Automatically fetch new apps from Pebble's App Store

- [x] Auto add archive tag to all Pebble App Store apps that are not Rebble Store Ready

- [x] Implement a DB that makes all of above work

Long term goals:

- [ ] #2 Ability for developers to upload their apps

- [ ] #3 Before a app shows up in the store it has to be approved

- [ ] Add doomsday backup opt-in (boolean should be in the DB from the start)

All of this using an API like [this one](https://github.com/pebble-dev/rebblestore-api/issues/7)

**Comment by phpeter** [comment]
I'd add to this: authentication with multiple levels (user/anon, developer, moderator/curator, administrator). We may also want to open up a separate issue for this to discuss further (we need to coordinate with the front-end team to figure out what the best method for authentication is. OAuth? Tokens?)
